/**
 * Wise-r API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChangeResourceV2'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChangeResourceV2'));
  } else {
    // Browser globals (root is window)
    if (!root.WiserClient) {
      root.WiserClient = {};
    }
    root.WiserClient.ChangeSetV2 = factory(root.WiserClient.ApiClient, root.WiserClient.ChangeResourceV2);
  }
}(this, function(ApiClient, ChangeResourceV2) {
  'use strict';




  /**
   * The ChangeSetV2 model module.
   * @module model/ChangeSetV2
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChangeSetV2</code>.
   * @alias module:model/ChangeSetV2
   * @class
   * @param changes {Array.<module:model/ChangeResourceV2>} The list of changes
   * @param nextId {Integer} The nextId to be used in followup requests.
   */
  var exports = function(changes, nextId) {
    var _this = this;

    _this['changes'] = changes;
    _this['nextId'] = nextId;
  };

  /**
   * Constructs a <code>ChangeSetV2</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChangeSetV2} obj Optional instance to populate.
   * @return {module:model/ChangeSetV2} The populated <code>ChangeSetV2</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('changes')) {
        obj['changes'] = ApiClient.convertToType(data['changes'], [ChangeResourceV2]);
      }
      if (data.hasOwnProperty('nextId')) {
        obj['nextId'] = ApiClient.convertToType(data['nextId'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * The list of changes
   * @member {Array.<module:model/ChangeResourceV2>} changes
   */
  exports.prototype['changes'] = undefined;
  /**
   * The nextId to be used in followup requests.
   * @member {Integer} nextId
   */
  exports.prototype['nextId'] = undefined;



  return exports;
}));


