/**
 * Wise-r API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['WiserClient', 'model/RestResourceLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RestResourceLink'));
  } else {
    // Browser globals (root is window)
    if (!root.WiserClient) {
      root.WiserClient = {};
    }
    root.WiserClient.GroupResource = factory(root.WiserClient.ApiClient, root.WiserClient.RestResourceLink);
  }
}(this, function(ApiClient, RestResourceLink) {
  'use strict';




  /**
   * The GroupResource model module.
   * @module model/GroupResource
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GroupResource</code>.
   * @alias module:model/GroupResource
   * @class
   * @param id {String} The ID of this resource
   * @param organisationId {String} The ID of the Organisation
   */
  var exports = function(id, organisationId) {
    var _this = this;


    _this['id'] = id;







    _this['organisationId'] = organisationId;
  };

  /**
   * Constructs a <code>GroupResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupResource} obj Optional instance to populate.
   * @return {module:model/GroupResource} The populated <code>GroupResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('organisatieKey')) {
        obj['organisatieKey'] = ApiClient.convertToType(data['organisatieKey'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('schoolyear')) {
        obj['schoolyear'] = ApiClient.convertToType(data['schoolyear'], 'String');
      }
      if (data.hasOwnProperty('schoolId')) {
        obj['schoolId'] = ApiClient.convertToType(data['schoolId'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('linkedResources')) {
        obj['linkedResources'] = ApiClient.convertToType(data['linkedResources'], [RestResourceLink]);
      }
      if (data.hasOwnProperty('linkedSchoolLocationIds')) {
        obj['linkedSchoolLocationIds'] = ApiClient.convertToType(data['linkedSchoolLocationIds'], [RestResourceLink]);
      }
      if (data.hasOwnProperty('urlToKey')) {
        obj['urlToKey'] = ApiClient.convertToType(data['urlToKey'], 'String');
      }
      if (data.hasOwnProperty('organisationId')) {
        obj['organisationId'] = ApiClient.convertToType(data['organisationId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} organisatieKey
   */
  exports.prototype['organisatieKey'] = undefined;
  /**
   * The ID of this resource
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * schoolyear, for example 2014-2015
   * @member {String} schoolyear
   */
  exports.prototype['schoolyear'] = undefined;
  /**
   * Parent school of this location.
   * @member {String} schoolId
   */
  exports.prototype['schoolId'] = undefined;
  /**
   * grouptype
   * @member {module:model/GroupResource.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * List of id's of Resources (Groups or Users) that belong to this Group
   * @member {Array.<module:model/RestResourceLink>} linkedResources
   */
  exports.prototype['linkedResources'] = undefined;
  /**
   * List of linked schoolLocationId's of the current group. 
   * @member {Array.<module:model/RestResourceLink>} linkedSchoolLocationIds
   */
  exports.prototype['linkedSchoolLocationIds'] = undefined;
  /**
   * @member {String} urlToKey
   */
  exports.prototype['urlToKey'] = undefined;
  /**
   * The ID of the Organisation
   * @member {String} organisationId
   */
  exports.prototype['organisationId'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "group"
     * @const
     */
    "group": "group",
    /**
     * value: "class"
     * @const
     */
    "class": "class",
    /**
     * value: "planner"
     * @const
     */
    "planner": "planner"  };


  return exports;
}));


