/**
 * Wise-r API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WiserClient) {
      root.WiserClient = {};
    }
    root.WiserClient.MediaType = factory(root.WiserClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MediaType model module.
   * @module model/MediaType
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MediaType</code>.
   * @alias module:model/MediaType
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>MediaType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediaType} obj Optional instance to populate.
   * @return {module:model/MediaType} The populated <code>MediaType</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('subtype')) {
        obj['subtype'] = ApiClient.convertToType(data['subtype'], 'String');
      }
      if (data.hasOwnProperty('parameters')) {
        obj['parameters'] = ApiClient.convertToType(data['parameters'], {'String': 'String'});
      }
      if (data.hasOwnProperty('wildcardType')) {
        obj['wildcardType'] = ApiClient.convertToType(data['wildcardType'], 'Boolean');
      }
      if (data.hasOwnProperty('wildcardSubtype')) {
        obj['wildcardSubtype'] = ApiClient.convertToType(data['wildcardSubtype'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} subtype
   */
  exports.prototype['subtype'] = undefined;
  /**
   * @member {Object.<String, String>} parameters
   */
  exports.prototype['parameters'] = undefined;
  /**
   * @member {Boolean} wildcardType
   * @default false
   */
  exports.prototype['wildcardType'] = false;
  /**
   * @member {Boolean} wildcardSubtype
   * @default false
   */
  exports.prototype['wildcardSubtype'] = false;



  return exports;
}));


