/**
 * Wise-r API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WiserClient) {
      root.WiserClient = {};
    }
    root.WiserClient.SchoolLocationResource = factory(root.WiserClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SchoolLocationResource model module.
   * @module model/SchoolLocationResource
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SchoolLocationResource</code>.
   * @alias module:model/SchoolLocationResource
   * @class
   * @param id {String} The ID of this resource
   * @param organisationId {String} The ID of the Organisation
   */
  var exports = function(id, organisationId) {
    var _this = this;


    _this['id'] = id;






    _this['organisationId'] = organisationId;
  };

  /**
   * Constructs a <code>SchoolLocationResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SchoolLocationResource} obj Optional instance to populate.
   * @return {module:model/SchoolLocationResource} The populated <code>SchoolLocationResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('organisatieKey')) {
        obj['organisatieKey'] = ApiClient.convertToType(data['organisatieKey'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('schoolId')) {
        obj['schoolId'] = ApiClient.convertToType(data['schoolId'], 'String');
      }
      if (data.hasOwnProperty('brincode')) {
        obj['brincode'] = ApiClient.convertToType(data['brincode'], 'String');
      }
      if (data.hasOwnProperty('dependancecode')) {
        obj['dependancecode'] = ApiClient.convertToType(data['dependancecode'], 'String');
      }
      if (data.hasOwnProperty('schoolkey')) {
        obj['schoolkey'] = ApiClient.convertToType(data['schoolkey'], 'String');
      }
      if (data.hasOwnProperty('urlToKey')) {
        obj['urlToKey'] = ApiClient.convertToType(data['urlToKey'], 'String');
      }
      if (data.hasOwnProperty('organisationId')) {
        obj['organisationId'] = ApiClient.convertToType(data['organisationId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} organisatieKey
   */
  exports.prototype['organisatieKey'] = undefined;
  /**
   * The ID of this resource
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Name of the SchoolLocation
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Parent school of this location.
   * @member {String} schoolId
   */
  exports.prototype['schoolId'] = undefined;
  /**
   * BRIN code
   * @member {String} brincode
   */
  exports.prototype['brincode'] = undefined;
  /**
   * Dependance code
   * @member {String} dependancecode
   */
  exports.prototype['dependancecode'] = undefined;
  /**
   * Schoolkey, only used when the combination of BRIN code and dependance code is not unique
   * @member {String} schoolkey
   */
  exports.prototype['schoolkey'] = undefined;
  /**
   * @member {String} urlToKey
   */
  exports.prototype['urlToKey'] = undefined;
  /**
   * The ID of the Organisation
   * @member {String} organisationId
   */
  exports.prototype['organisationId'] = undefined;



  return exports;
}));


