/**
 * Wise-r API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['WiserClient', 'model/RestResourceLink', 'model/SchoolLocationResource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RestResourceLink'), require('./SchoolLocationResource'));
  } else {
    // Browser globals (root is window)
    if (!root.WiserClient) {
      root.WiserClient = {};
    }
    root.WiserClient.UserResource = factory(root.WiserClient.ApiClient, root.WiserClient.RestResourceLink, root.WiserClient.SchoolLocationResource);
  }
}(this, function(ApiClient, RestResourceLink, SchoolLocationResource) {
  'use strict';




  /**
   * The UserResource model module.
   * @module model/UserResource
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UserResource</code>.
   * @alias module:model/UserResource
   * @class
   * @param id {String} The ID of this resource
   * @param organisationId {String} The ID of the Organisation
   */
  var exports = function(id, organisationId) {
    var _this = this;


    _this['id'] = id;














    _this['organisationId'] = organisationId;
  };

  /**
   * Constructs a <code>UserResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserResource} obj Optional instance to populate.
   * @return {module:model/UserResource} The populated <code>UserResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('organisatieKey')) {
        obj['organisatieKey'] = ApiClient.convertToType(data['organisatieKey'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('initials')) {
        obj['initials'] = ApiClient.convertToType(data['initials'], 'String');
      }
      if (data.hasOwnProperty('firstname')) {
        obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
      }
      if (data.hasOwnProperty('surname')) {
        obj['surname'] = ApiClient.convertToType(data['surname'], 'String');
      }
      if (data.hasOwnProperty('prefix')) {
        obj['prefix'] = ApiClient.convertToType(data['prefix'], 'String');
      }
      if (data.hasOwnProperty('birthdate')) {
        obj['birthdate'] = ApiClient.convertToType(data['birthdate'], 'Date');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('userType')) {
        obj['userType'] = ApiClient.convertToType(data['userType'], 'String');
      }
      if (data.hasOwnProperty('grade')) {
        obj['grade'] = ApiClient.convertToType(data['grade'], 'String');
      }
      if (data.hasOwnProperty('gender')) {
        obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
      }
      if (data.hasOwnProperty('sector')) {
        obj['sector'] = ApiClient.convertToType(data['sector'], 'String');
      }
      if (data.hasOwnProperty('schoolLocations')) {
        obj['schoolLocations'] = ApiClient.convertToType(data['schoolLocations'], [SchoolLocationResource]);
      }
      if (data.hasOwnProperty('linkedGroups')) {
        obj['linkedGroups'] = ApiClient.convertToType(data['linkedGroups'], [RestResourceLink]);
      }
      if (data.hasOwnProperty('linkedSchoolLocationIds')) {
        obj['linkedSchoolLocationIds'] = ApiClient.convertToType(data['linkedSchoolLocationIds'], [RestResourceLink]);
      }
      if (data.hasOwnProperty('urlToKey')) {
        obj['urlToKey'] = ApiClient.convertToType(data['urlToKey'], 'String');
      }
      if (data.hasOwnProperty('organisationId')) {
        obj['organisationId'] = ApiClient.convertToType(data['organisationId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} organisatieKey
   */
  exports.prototype['organisatieKey'] = undefined;
  /**
   * The ID of this resource
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} initials
   */
  exports.prototype['initials'] = undefined;
  /**
   * @member {String} firstname
   */
  exports.prototype['firstname'] = undefined;
  /**
   * @member {String} surname
   */
  exports.prototype['surname'] = undefined;
  /**
   * @member {String} prefix
   */
  exports.prototype['prefix'] = undefined;
  /**
   * @member {Date} birthdate
   */
  exports.prototype['birthdate'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {module:model/UserResource.UserTypeEnum} userType
   */
  exports.prototype['userType'] = undefined;
  /**
   * Current grade the student is in
   * @member {String} grade
   */
  exports.prototype['grade'] = undefined;
  /**
   * @member {module:model/UserResource.GenderEnum} gender
   */
  exports.prototype['gender'] = undefined;
  /**
   * Sector of education of this identity. PO/SO/VO/BO/HO/ANDERS/ONBEKEND
   * @member {String} sector
   */
  exports.prototype['sector'] = undefined;
  /**
   * List of SchoolLocations this User belongs to
   * @member {Array.<module:model/SchoolLocationResource>} schoolLocations
   */
  exports.prototype['schoolLocations'] = undefined;
  /**
   * List of id's of Groups which this User belongs to
   * @member {Array.<module:model/RestResourceLink>} linkedGroups
   */
  exports.prototype['linkedGroups'] = undefined;
  /**
   * List of id's of SchoolLocations this User belongs to. Deprecated, use 'schoolLocations'.
   * @member {Array.<module:model/RestResourceLink>} linkedSchoolLocationIds
   */
  exports.prototype['linkedSchoolLocationIds'] = undefined;
  /**
   * @member {String} urlToKey
   */
  exports.prototype['urlToKey'] = undefined;
  /**
   * The ID of the Organisation
   * @member {String} organisationId
   */
  exports.prototype['organisationId'] = undefined;


  /**
   * Allowed values for the <code>userType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.UserTypeEnum = {
    /**
     * value: "student"
     * @const
     */
    "student": "student",
    /**
     * value: "teacher"
     * @const
     */
    "teacher": "teacher"  };

  /**
   * Allowed values for the <code>gender</code> property.
   * @enum {String}
   * @readonly
   */
  exports.GenderEnum = {
    /**
     * value: "male"
     * @const
     */
    "male": "male",
    /**
     * value: "female"
     * @const
     */
    "female": "female",
    /**
     * value: "unknown"
     * @const
     */
    "unknown": "unknown"  };


  return exports;
}));


