/**
 * Wise-r API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WiserClient);
  }
}(this, function(expect, WiserClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WiserClient.ChangeResourceV2();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChangeResourceV2', function() {
    it('should create an instance of ChangeResourceV2', function() {
      // uncomment below and update the code to test ChangeResourceV2
      //var instane = new WiserClient.ChangeResourceV2();
      //expect(instance).to.be.a(WiserClient.ChangeResourceV2);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new WiserClient.ChangeResourceV2();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instane = new WiserClient.ChangeResourceV2();
      //expect(instance).to.be();
    });

    it('should have the property changeType (base name: "changeType")', function() {
      // uncomment below and update the code to test the property changeType
      //var instane = new WiserClient.ChangeResourceV2();
      //expect(instance).to.be();
    });

    it('should have the property changedResourceType (base name: "changedResourceType")', function() {
      // uncomment below and update the code to test the property changedResourceType
      //var instane = new WiserClient.ChangeResourceV2();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instane = new WiserClient.ChangeResourceV2();
      //expect(instance).to.be();
    });

    it('should have the property linkedSchoolLocation (base name: "linkedSchoolLocation")', function() {
      // uncomment below and update the code to test the property linkedSchoolLocation
      //var instane = new WiserClient.ChangeResourceV2();
      //expect(instance).to.be();
    });

  });

}));
