/**
 * Wise-r API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WiserClient);
  }
}(this, function(expect, WiserClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WiserClient.GroupResource();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GroupResource', function() {
    it('should create an instance of GroupResource', function() {
      // uncomment below and update the code to test GroupResource
      //var instane = new WiserClient.GroupResource();
      //expect(instance).to.be.a(WiserClient.GroupResource);
    });

    it('should have the property organisatieKey (base name: "organisatieKey")', function() {
      // uncomment below and update the code to test the property organisatieKey
      //var instane = new WiserClient.GroupResource();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new WiserClient.GroupResource();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new WiserClient.GroupResource();
      //expect(instance).to.be();
    });

    it('should have the property schoolyear (base name: "schoolyear")', function() {
      // uncomment below and update the code to test the property schoolyear
      //var instane = new WiserClient.GroupResource();
      //expect(instance).to.be();
    });

    it('should have the property schoolId (base name: "schoolId")', function() {
      // uncomment below and update the code to test the property schoolId
      //var instane = new WiserClient.GroupResource();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new WiserClient.GroupResource();
      //expect(instance).to.be();
    });

    it('should have the property linkedResources (base name: "linkedResources")', function() {
      // uncomment below and update the code to test the property linkedResources
      //var instane = new WiserClient.GroupResource();
      //expect(instance).to.be();
    });

    it('should have the property linkedSchoolLocationIds (base name: "linkedSchoolLocationIds")', function() {
      // uncomment below and update the code to test the property linkedSchoolLocationIds
      //var instane = new WiserClient.GroupResource();
      //expect(instance).to.be();
    });

    it('should have the property urlToKey (base name: "urlToKey")', function() {
      // uncomment below and update the code to test the property urlToKey
      //var instane = new WiserClient.GroupResource();
      //expect(instance).to.be();
    });

    it('should have the property organisationId (base name: "organisationId")', function() {
      // uncomment below and update the code to test the property organisationId
      //var instane = new WiserClient.GroupResource();
      //expect(instance).to.be();
    });

  });

}));
