/**
 * Wise-r API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WiserClient);
  }
}(this, function(expect, WiserClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WiserClient.Locale();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Locale', function() {
    it('should create an instance of Locale', function() {
      // uncomment below and update the code to test Locale
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be.a(WiserClient.Locale);
    });

    it('should have the property script (base name: "script")', function() {
      // uncomment below and update the code to test the property script
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property variant (base name: "variant")', function() {
      // uncomment below and update the code to test the property variant
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property extensionKeys (base name: "extensionKeys")', function() {
      // uncomment below and update the code to test the property extensionKeys
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property unicodeLocaleAttributes (base name: "unicodeLocaleAttributes")', function() {
      // uncomment below and update the code to test the property unicodeLocaleAttributes
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property unicodeLocaleKeys (base name: "unicodeLocaleKeys")', function() {
      // uncomment below and update the code to test the property unicodeLocaleKeys
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property iso3Language (base name: "iso3Language")', function() {
      // uncomment below and update the code to test the property iso3Language
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property iso3Country (base name: "iso3Country")', function() {
      // uncomment below and update the code to test the property iso3Country
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property displayLanguage (base name: "displayLanguage")', function() {
      // uncomment below and update the code to test the property displayLanguage
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property displayScript (base name: "displayScript")', function() {
      // uncomment below and update the code to test the property displayScript
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property displayCountry (base name: "displayCountry")', function() {
      // uncomment below and update the code to test the property displayCountry
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property displayVariant (base name: "displayVariant")', function() {
      // uncomment below and update the code to test the property displayVariant
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property displayName (base name: "displayName")', function() {
      // uncomment below and update the code to test the property displayName
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instane = new WiserClient.Locale();
      //expect(instance).to.be();
    });

  });

}));
