/**
 * Wise-r API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AanbiederIdRestResourceLink', 'model/ChangeResourceV2', 'model/ChangeSetV2', 'model/EntityTag', 'model/GroupResourceV2', 'model/KeyValueResourceV2', 'model/KeyringResourceV2', 'model/Link', 'model/Locale', 'model/MediaType', 'model/NewCookie', 'model/NotAuthorizedOrganisationResponse', 'model/Response', 'model/RestResourceLinkV2', 'model/SchoolLocationResourceV2', 'model/SchoolResource', 'model/StatusType', 'model/UriBuilder', 'model/UserResourceV2', 'api/ChangesApi', 'api/DocumentsApi', 'api/GroupsApi', 'api/SchoolsApi', 'api/UsersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AanbiederIdRestResourceLink'), require('./model/ChangeResourceV2'), require('./model/ChangeSetV2'), require('./model/EntityTag'), require('./model/GroupResourceV2'), require('./model/KeyValueResourceV2'), require('./model/KeyringResourceV2'), require('./model/Link'), require('./model/Locale'), require('./model/MediaType'), require('./model/NewCookie'), require('./model/NotAuthorizedOrganisationResponse'), require('./model/Response'), require('./model/RestResourceLinkV2'), require('./model/SchoolLocationResourceV2'), require('./model/SchoolResource'), require('./model/StatusType'), require('./model/UriBuilder'), require('./model/UserResourceV2'), require('./api/ChangesApi'), require('./api/DocumentsApi'), require('./api/GroupsApi'), require('./api/SchoolsApi'), require('./api/UsersApi'));
  }
}(function(ApiClient, AanbiederIdRestResourceLink, ChangeResourceV2, ChangeSetV2, EntityTag, GroupResourceV2, KeyValueResourceV2, KeyringResourceV2, Link, Locale, MediaType, NewCookie, NotAuthorizedOrganisationResponse, Response, RestResourceLinkV2, SchoolLocationResourceV2, SchoolResource, StatusType, UriBuilder, UserResourceV2, ChangesApi, DocumentsApi, GroupsApi, SchoolsApi, UsersApi) {
  'use strict';

  /**
   * Wise-r OpenAPI Client.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var WiserClient = require('index'); // See note below*.
   * var xxxSvc = new WiserClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new WiserClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new WiserClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new WiserClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 2.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AanbiederIdRestResourceLink model constructor.
     * @property {module:model/AanbiederIdRestResourceLink}
     */
    AanbiederIdRestResourceLink: AanbiederIdRestResourceLink,
    /**
     * The ChangeResourceV2 model constructor.
     * @property {module:model/ChangeResourceV2}
     */
    ChangeResourceV2: ChangeResourceV2,
    /**
     * The ChangeSetV2 model constructor.
     * @property {module:model/ChangeSetV2}
     */
    ChangeSetV2: ChangeSetV2,
    /**
     * The EntityTag model constructor.
     * @property {module:model/EntityTag}
     */
    EntityTag: EntityTag,
    /**
     * The GroupResourceV2 model constructor.
     * @property {module:model/GroupResourceV2}
     */
    GroupResourceV2: GroupResourceV2,
    /**
     * The KeyValueResourceV2 model constructor.
     * @property {module:model/KeyValueResourceV2}
     */
    KeyValueResourceV2: KeyValueResourceV2,
    /**
     * The KeyringResourceV2 model constructor.
     * @property {module:model/KeyringResourceV2}
     */
    KeyringResourceV2: KeyringResourceV2,
    /**
     * The Link model constructor.
     * @property {module:model/Link}
     */
    Link: Link,
    /**
     * The Locale model constructor.
     * @property {module:model/Locale}
     */
    Locale: Locale,
    /**
     * The MediaType model constructor.
     * @property {module:model/MediaType}
     */
    MediaType: MediaType,
    /**
     * The NewCookie model constructor.
     * @property {module:model/NewCookie}
     */
    NewCookie: NewCookie,
    /**
     * The NotAuthorizedOrganisationResponse model constructor.
     * @property {module:model/NotAuthorizedOrganisationResponse}
     */
    NotAuthorizedOrganisationResponse: NotAuthorizedOrganisationResponse,
    /**
     * The Response model constructor.
     * @property {module:model/Response}
     */
    Response: Response,
    /**
     * The RestResourceLinkV2 model constructor.
     * @property {module:model/RestResourceLinkV2}
     */
    RestResourceLinkV2: RestResourceLinkV2,
    /**
     * The SchoolLocationResourceV2 model constructor.
     * @property {module:model/SchoolLocationResourceV2}
     */
    SchoolLocationResourceV2: SchoolLocationResourceV2,
    /**
     * The SchoolResource model constructor.
     * @property {module:model/SchoolResource}
     */
    SchoolResource: SchoolResource,
    /**
     * The StatusType model constructor.
     * @property {module:model/StatusType}
     */
    StatusType: StatusType,
    /**
     * The UriBuilder model constructor.
     * @property {module:model/UriBuilder}
     */
    UriBuilder: UriBuilder,
    /**
     * The UserResourceV2 model constructor.
     * @property {module:model/UserResourceV2}
     */
    UserResourceV2: UserResourceV2,
    /**
     * The ChangesApi service constructor.
     * @property {module:api/ChangesApi}
     */
    ChangesApi: ChangesApi,
    /**
     * The DocumentsApi service constructor.
     * @property {module:api/DocumentsApi}
     */
    DocumentsApi: DocumentsApi,
    /**
     * The GroupsApi service constructor.
     * @property {module:api/GroupsApi}
     */
    GroupsApi: GroupsApi,
    /**
     * The SchoolsApi service constructor.
     * @property {module:api/SchoolsApi}
     */
    SchoolsApi: SchoolsApi,
    /**
     * The UsersApi service constructor.
     * @property {module:api/UsersApi}
     */
    UsersApi: UsersApi
  };

  return exports;
}));
