/**
 * Wise-r API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChangeResource', 'model/ChangeSet', 'model/EntityTag', 'model/GroupResource', 'model/KeyResource', 'model/KeyringResource', 'model/Link', 'model/Locale', 'model/MediaType', 'model/NewCookie', 'model/NotAuthorizedOrganisationResponse', 'model/Response', 'model/RestResourceLink', 'model/SchoolLocationResource', 'model/SchoolResource', 'model/StatusType', 'model/UriBuilder', 'model/UserResource', 'api/ChangesApi', 'api/DocumentsApi', 'api/GroupsApi', 'api/SchoolsApi', 'api/UsersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ChangeResource'), require('./model/ChangeSet'), require('./model/EntityTag'), require('./model/GroupResource'), require('./model/KeyResource'), require('./model/KeyringResource'), require('./model/Link'), require('./model/Locale'), require('./model/MediaType'), require('./model/NewCookie'), require('./model/NotAuthorizedOrganisationResponse'), require('./model/Response'), require('./model/RestResourceLink'), require('./model/SchoolLocationResource'), require('./model/SchoolResource'), require('./model/StatusType'), require('./model/UriBuilder'), require('./model/UserResource'), require('./api/ChangesApi'), require('./api/DocumentsApi'), require('./api/GroupsApi'), require('./api/SchoolsApi'), require('./api/UsersApi'));
  }
}(function(ApiClient, ChangeResource, ChangeSet, EntityTag, GroupResource, KeyResource, KeyringResource, Link, Locale, MediaType, NewCookie, NotAuthorizedOrganisationResponse, Response, RestResourceLink, SchoolLocationResource, SchoolResource, StatusType, UriBuilder, UserResource, ChangesApi, DocumentsApi, GroupsApi, SchoolsApi, UsersApi) {
  'use strict';

  /**
   * Wise-r OpenAPI Client.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var WiserClient = require('index'); // See note below*.
   * var xxxSvc = new WiserClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new WiserClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new WiserClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new WiserClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ChangeResource model constructor.
     * @property {module:model/ChangeResource}
     */
    ChangeResource: ChangeResource,
    /**
     * The ChangeSet model constructor.
     * @property {module:model/ChangeSet}
     */
    ChangeSet: ChangeSet,
    /**
     * The EntityTag model constructor.
     * @property {module:model/EntityTag}
     */
    EntityTag: EntityTag,
    /**
     * The GroupResource model constructor.
     * @property {module:model/GroupResource}
     */
    GroupResource: GroupResource,
    /**
     * The KeyResource model constructor.
     * @property {module:model/KeyResource}
     */
    KeyResource: KeyResource,
    /**
     * The KeyringResource model constructor.
     * @property {module:model/KeyringResource}
     */
    KeyringResource: KeyringResource,
    /**
     * The Link model constructor.
     * @property {module:model/Link}
     */
    Link: Link,
    /**
     * The Locale model constructor.
     * @property {module:model/Locale}
     */
    Locale: Locale,
    /**
     * The MediaType model constructor.
     * @property {module:model/MediaType}
     */
    MediaType: MediaType,
    /**
     * The NewCookie model constructor.
     * @property {module:model/NewCookie}
     */
    NewCookie: NewCookie,
    /**
     * The NotAuthorizedOrganisationResponse model constructor.
     * @property {module:model/NotAuthorizedOrganisationResponse}
     */
    NotAuthorizedOrganisationResponse: NotAuthorizedOrganisationResponse,
    /**
     * The Response model constructor.
     * @property {module:model/Response}
     */
    Response: Response,
    /**
     * The RestResourceLink model constructor.
     * @property {module:model/RestResourceLink}
     */
    RestResourceLink: RestResourceLink,
    /**
     * The SchoolLocationResource model constructor.
     * @property {module:model/SchoolLocationResource}
     */
    SchoolLocationResource: SchoolLocationResource,
    /**
     * The SchoolResource model constructor.
     * @property {module:model/SchoolResource}
     */
    SchoolResource: SchoolResource,
    /**
     * The StatusType model constructor.
     * @property {module:model/StatusType}
     */
    StatusType: StatusType,
    /**
     * The UriBuilder model constructor.
     * @property {module:model/UriBuilder}
     */
    UriBuilder: UriBuilder,
    /**
     * The UserResource model constructor.
     * @property {module:model/UserResource}
     */
    UserResource: UserResource,
    /**
     * The ChangesApi service constructor.
     * @property {module:api/ChangesApi}
     */
    ChangesApi: ChangesApi,
    /**
     * The DocumentsApi service constructor.
     * @property {module:api/DocumentsApi}
     */
    DocumentsApi: DocumentsApi,
    /**
     * The GroupsApi service constructor.
     * @property {module:api/GroupsApi}
     */
    GroupsApi: GroupsApi,
    /**
     * The SchoolsApi service constructor.
     * @property {module:api/SchoolsApi}
     */
    SchoolsApi: SchoolsApi,
    /**
     * The UsersApi service constructor.
     * @property {module:api/UsersApi}
     */
    UsersApi: UsersApi
  };

  return exports;
}));
